# -*- coding: utf-8 -*-
"""tiki_discovery_crawler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc8JKnwSkjm6_I0vamwI-Q-gpIzdN-Pc

# Tiki Discovery Crawler (Selenium + MS Edge) chạy trên Google Colab

Notebook này crawl các URL sản phẩm trên Tiki (BFS từ 1 URL seed) và **lưu kết quả vào Google Drive**.
Nếu Colab bị ngắt giữa chừng, chỉ cần chạy lại các cell từ đầu: crawler sẽ **đọc lại dữ liệu trên Drive và chạy tiếp**, không crawl lại những trang đã xong.

## Hướng dẫn: vì sao cần cài MS Edge và Edge Driver?

Selenium điều khiển trình duyệt thật. Code gốc dùng **Microsoft Edge** nên cần 2 thứ:

1. **Microsoft Edge** (trình duyệt). Colab là Linux và mỗi lần mở phiên mới thì máy bị reset, nên **cell 2 sẽ cài Edge lại mỗi phiên** (mất khoảng 1 phút).
2. **Edge WebDriver (`msedgedriver`)** là cầu nối giữa Selenium và Edge. **Phiên bản driver phải khớp với phiên bản Edge**. Cell 4 tự tải đúng bản và để vào thư mục `edgedriver_linux64` trên Drive (tương ứng `edgedriver_win64` trong code gốc), nên lần sau không phải tải lại nếu phiên bản vẫn khớp.

Cấu trúc trên Drive:

```
MyDrive/tiki_crawler/
├── edgedriver_linux64/
│   └── msedgedriver            <- Edge driver (tự tải)
└── data/
    ├── urls_found.txt          <- mọi URL đã phát hiện
    ├── urls_done.txt           <- URL đã crawl xong (dùng để resume)
    └── urls_failed.txt         <- URL lỗi quá số lần thử
```

> Nếu muốn chạy trên Windows (máy cá nhân) thay vì Colab: cài Edge, tải driver khớp phiên bản tại https://developer.microsoft.com/microsoft-edge/tools/webdriver/ rồi giải nén vào `edgedriver_win64`, như code gốc. Notebook này chỉ dành cho Colab (Linux).

## 1. Mount Google Drive và cấu hình
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# ====== CẤU HÌNH ======
BASE_DIR        = '/content/drive/MyDrive/tiki_crawler'
EDGE_DRIVER_DIR = f'{BASE_DIR}/edgedriver_linux64'
DATA_DIR        = f'{BASE_DIR}/data'

LOCAL_DRIVER_DIR = '/content/edgedriver_linux64'
DRIVER_PATH      = f'{LOCAL_DRIVER_DIR}/msedgedriver'
USER_DATA_DIR    = '/content/selenium_user_data'

# DANH SÁCH ROOT SEED URL: Các gốc lớn bao phủ toàn bộ ngành Thời trang trên Tiki
# (Nam, Nữ, Trẻ em sơ sinh - bé trai - bé gái, Giày dép, Túi xách balo, Phụ kiện & Đồng hồ)
SEED_URLS = [
    'https://tiki.vn/thoi-trang-nam/c915',        # Toàn bộ Thời trang Nam
    'https://tiki.vn/thoi-trang-nu/c931',         # Toàn bộ Thời trang Nữ
    'https://tiki.vn/thoi-trang-cho-be/c11603',   # Toàn bộ Thời trang Trẻ em & Sơ sinh
    'https://tiki.vn/giay-dep-nam/c1686',         # Giày dép Nam
    'https://tiki.vn/giay-dep-nu/c1703',          # Giày dép Nữ
    'https://tiki.vn/tui-thoi-trang-nu/c976',      # Túi xách, Ví, Balo
    'https://tiki.vn/balo-va-vali/c914',          # Balo & Vali
    'https://tiki.vn/phu-kien-thoi-trang/c27498', # Phụ kiện thời trang
    'https://tiki.vn/dong-ho-va-trang-suc/c8371'  # Trang sức & Đồng hồ
]

# Tham số crawl tối ưu cho dữ liệu lớn
BATCH_SIZE = 50                        # Số dòng gom lại trước khi ghi Drive
BATCH_TIMEOUT = 2.0
CLEAR_CACHE_EVERY_N_PAGES = 15         # Dọn cache định kỳ
RESTART_DRIVER_EVERY_N_PAGES = 40      # Restart driver định kỳ để giải phóng RAM
RESTART_DRIVER_RAM_MB = 2200           # Ngưỡng RAM tối đa cho phép
MAX_RETRIES = 2
MAX_CONSECUTIVE_FAILURES = 3
MAX_RESTARTS_WITHOUT_SUCCESS = 5
MAX_RUNTIME_MINUTES = None             # None = chạy liên tục đến khi hết hoặc bạn bấm Stop

for d in (BASE_DIR, EDGE_DRIVER_DIR, DATA_DIR, LOCAL_DRIVER_DIR):
    os.makedirs(d, exist_ok=True)
print('OK. Dữ liệu sẽ lưu tại:', DATA_DIR)

"""## 2. Cài Microsoft Edge (chạy lại mỗi khi mở phiên Colab mới)"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# apt-get update -qq
# apt-get install -y -qq wget gnupg unzip curl > /dev/null
# curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --yes -o /usr/share/keyrings/microsoft-edge.gpg
# echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
# apt-get update -qq
# apt-get install -y -qq microsoft-edge-stable > /dev/null
# microsoft-edge --version

"""## 3. Cài thư viện Python"""

!pip -q install selenium psutil

"""## 4. Tải Edge Driver khớp phiên bản Edge, lưu vào `edgedriver_linux64` trên Drive

- Nếu trên Drive đã có driver và đúng phiên bản thì dùng luôn.
- Nếu lệch phiên bản (Edge tự cập nhật) thì tự tải bản mới và ghi đè.
"""

import subprocess, re, shutil, zipfile, io, urllib.request

def get_edge_version():
    out = subprocess.check_output(['microsoft-edge', '--version'], text=True)
    return re.search(r'(\d+\.\d+\.\d+\.\d+)', out).group(1)

def get_driver_version(path):
    if not os.path.exists(path):
        return None
    try:
        out = subprocess.check_output([path, '--version'], text=True, timeout=30)
        return re.search(r'(\d+\.\d+\.\d+\.\d+)', out).group(1)
    except Exception:
        return None

def http_get(url):
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=180) as r:
        return r.read()

BASES = ['https://msedgedriver.microsoft.com', 'https://msedgedriver.azureedge.net']

def download_driver_zip(edge_ver):
    major = edge_ver.split('.')[0]
    versions = [edge_ver]
    tried = set()
    while versions:
        v = versions.pop(0)
        if v in tried:
            continue
        tried.add(v)
        for base in BASES:
            try:
                print(f'Thử tải driver {v} từ {base} ...')
                return http_get(f'{base}/{v}/edgedriver_linux64.zip')
            except Exception as e:
                print('  lỗi:', e)
        # không có đúng bản -> lấy bản mới nhất cùng major
        if len(tried) == 1:
            for base in BASES:
                try:
                    raw = http_get(f'{base}/LATEST_RELEASE_{major}_LINUX')
                    latest = raw.decode('utf-16').strip().lstrip('\ufeff')
                    versions.append(latest)
                    break
                except Exception as e:
                    print('  không lấy được LATEST_RELEASE:', e)
    raise RuntimeError('Không tải được Edge driver phù hợp')

def install_local_copy():
    shutil.copy2(f'{EDGE_DRIVER_DIR}/msedgedriver', DRIVER_PATH)
    os.chmod(DRIVER_PATH, 0o755)

edge_ver = get_edge_version()
edge_major = edge_ver.split('.')[0]
print('Edge version  :', edge_ver)

drive_driver = f'{EDGE_DRIVER_DIR}/msedgedriver'
driver_ver = None
if os.path.exists(drive_driver):
    install_local_copy()
    driver_ver = get_driver_version(DRIVER_PATH)
print('Driver (Drive):', driver_ver)

if driver_ver is None or driver_ver.split('.')[0] != edge_major:
    print('Driver thiếu hoặc lệch phiên bản -> tải mới')
    data = download_driver_zip(edge_ver)
    with zipfile.ZipFile(io.BytesIO(data)) as z:
        z.extractall(EDGE_DRIVER_DIR)
    install_local_copy()
    driver_ver = get_driver_version(DRIVER_PATH)

print('Driver đang dùng:', driver_ver, '->', DRIVER_PATH)
assert driver_ver and driver_ver.split('.')[0] == edge_major, 'Driver và Edge không khớp phiên bản'

"""## 5. Ghi file `base_crawler.py` (class của bạn) và import

Cell dưới ghi file `base_crawler.py` vào `/content` (giữ nguyên code của bạn, chỉ chỉnh vài chỗ nhỏ cho Colab, tìm chữ `[COLAB]` trong file để thấy):

1. `logging.basicConfig(force=True)` để log hiện trong Colab.
2. Chỉ định binary Edge trên Linux (`/opt/microsoft/msedge/msedge`).
3. Bật `--disable-gpu` vì Colab không có GPU.
4. `_handle_signal`: khi bấm nút **Stop** của Colab (SIGINT), sau khi dọn dẹp sẽ `raise KeyboardInterrupt` thay vì `SystemExit`, để cell dừng đúng cách và không làm chết kernel.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/base_crawler.py
# """
# base_crawler.py
# ----------------
# Lop Crawler co so dung Selenium (Edge), co vong doi ro rang:
#     - start()   : khoi tao driver (tu don rac tien trinh/lock con sot truoc khi mo moi)
#     - run()     : logic crawl (override o lop con)
#     - stop()    : dung driver va don dep TOAN BO tai nguyen, KE CA khi driver bi treo
# 
# Dam bao don dep that su sach (khong con tien trinh msedge.exe / msedgedriver.exe mo cot)
# ngay ca khi:
#     - driver.quit() bi treo hoac loi (vi du dang load trang khi bi ngat)
#     - Chuong trinh bi Ctrl+C (KeyboardInterrupt / SIGINT) hoac bi kill (SIGTERM)
#     - Co exception xay ra trong luc crawl
#     - Dung `with BaseCrawler(...) as crawler:` (context manager)
# 
# Cach lam sach "trong sach" (giong doc2) gom 3 lop:
#     1. Sau khi goi driver.quit(), kill thang toan bo cay tien trinh con cua
#        msedgedriver.exe theo PID (khong cho no co co hoi treo).
#     2. Quet toan bo tien trinh msedge*/msedgedriver* con dang tro toi dung
#        user-data-dir cua phien nay va kill not (phong truong hop quit() khong
#        kip tao driver, hoac tien trinh mo coi tu lan chay truoc do crash).
#     3. Xoa cac file lock (SingletonLock, SingletonCookie, SingletonSocket) trong
#        profile de lan sau khoi dong khong bi Edge tuong profile dang duoc dung.
# 
# Cach dung:
#     class MyCrawler(BaseCrawler):
#         def run(self):
#             self.driver.get("https://example.com")
#             print(self.driver.title)
# 
#     with MyCrawler(headless=True) as c:
#         c.run()
# 
# Yeu cau cai them: pip install psutil
# 
# [COLAB] Cac cho da chinh so voi ban goc (tim "[COLAB]" de thay):
#     1. logging.basicConfig(force=True) de log hien trong Colab.
#     2. Chi tro binary Edge Linux (/opt/microsoft/msedge/msedge) neu co.
#     3. Bat --disable-gpu (Colab khong co GPU).
#     4. _handle_signal: voi SIGINT (nut Stop cua Colab) thi sau khi don dep se
#        raise KeyboardInterrupt thay vi SystemExit, de cell dung dung cach va
#        khong lam chet kernel.
# """
# 
# import atexit
# import logging
# import os
# import shutil
# import signal
# import tempfile
# from abc import ABC
# from pathlib import Path
# from typing import Optional
# 
# import psutil
# from selenium import webdriver
# from selenium.webdriver.edge.options import Options
# from selenium.webdriver.edge.service import Service
# from selenium.common.exceptions import WebDriverException
# 
# logging.basicConfig(
#     level=logging.INFO,
#     format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
#     force=True,  # [COLAB]
# )
# logger = logging.getLogger("BaseCrawler")
# 
# EDGE_LINUX_BINARY = "/opt/microsoft/msedge/msedge"  # [COLAB]
# 
# 
# class BaseCrawler(ABC):
#     """
#     Lop crawler co so. Ke thua va override phuong thuc `run()` de viet logic crawl rieng.
#     """
# 
#     def __init__(
#         self,
#         headless: bool = True,
#         driver_path: Optional[str] = None,
#         user_data_dir: Optional[str] = None,
#         profile_name: str = "profile",
#         cleanup_user_data_dir: bool = False,
#         window_size: str = "1920,1080",
#         user_agent: Optional[str] = None,
#         extra_options: Optional[list] = None,
#         page_load_timeout: int = 30,
#         implicit_wait: int = 5,
#     ):
#         """
#         user_data_dir:
#             Thu muc GOC do ban tu chi dinh va SO HUU. Crawler KHONG BAO GIO xoa
#             thu muc nay, du cleanup_user_data_dir=True. Neu de None, crawler se
#             tu tao mot thu muc TAM (o dau do trong he thong) va XOA sach khi stop().
#         profile_name:
#             Ten thu muc con (nam BEN TRONG user_data_dir) ma crawler tu tao ra de
#             luu profile Edge that su (--user-data-dir thuc te tro vao day). Dung
#             chung profile_name giua cac lan chay -> session/cookie duoc giu lai.
#         cleanup_user_data_dir:
#             Chi ap dung khi ban TU chi dinh user_data_dir. Mac dinh False (giu lai
#             thu muc con `profile_name` de dung lai lan sau). Dat True neu muon xoa
#             RIENG thu muc con do sau khi stop() - thu muc GOC user_data_dir van
#             luon duoc giu nguyen.
#         """
#         self.headless = headless
#         self.driver_path = driver_path
#         self.user_data_dir = user_data_dir
#         self.profile_name = profile_name
#         self._cleanup_user_data_dir = cleanup_user_data_dir
#         self._is_temp_profile = user_data_dir is None
# 
#         self.window_size = window_size
#         self.user_agent = user_agent
#         self.extra_options = extra_options or []
#         self.page_load_timeout = page_load_timeout
#         self.implicit_wait = implicit_wait
# 
#         self.driver: Optional[webdriver.Edge] = None
#         self._profile_dir: Optional[str] = None
#         self._is_running: bool = False
#         self._stopped: bool = False
# 
#         # Dam bao cleanup du chuong trinh thoat bat thuong
#         atexit.register(self.stop)
#         signal.signal(signal.SIGINT, self._handle_signal)
#         signal.signal(signal.SIGTERM, self._handle_signal)
# 
#     # ------------------------------------------------------------------ #
#     # Vong doi chinh
#     # ------------------------------------------------------------------ #
# 
#     def start(self) -> None:
#         """Khoi tao Selenium WebDriver (Edge)."""
#         if self._is_running:
#             logger.warning("Crawler is already running, skipping start().")
#             return
# 
#         # Xac dinh thu muc profile se dung TRUOC khi mo driver, de co the don
#         # rac tien trinh/lock con sot tu lan chay truoc (neu dung chung profile).
#         self._resolve_profile_dir()
#         self._cleanup_orphan_processes()
# 
#         logger.info("Initializing driver...")
#         options = self._build_options()
# 
#         try:
#             if self.driver_path:
#                 service = Service(executable_path=self.driver_path)
#                 self.driver = webdriver.Edge(service=service, options=options)
#             else:
#                 self.driver = webdriver.Edge(options=options)
# 
#             self.driver.set_page_load_timeout(self.page_load_timeout)
#             self.driver.implicitly_wait(self.implicit_wait)
#             self._is_running = True
#             self._stopped = False
#             logger.info("Driver Init done. Crawler is running.")
#         except WebDriverException as e:
#             logger.error(f"Cannot initialize driver: {e}")
#             self.stop()
#             raise
# 
#     def restart_driver(self):
#         logger.info("Restarting driver...")
#         self.stop()
#         self.start()
#         logger.info("Driver restarted successfully.")
# 
#     def run(self, *args) -> None:
#         """
#         Logic crawl chinh. BAT BUOC override o lop con.
#         Vi du:
#             self.driver.get("https://example.com")
#         """
#         raise NotImplementedError("Subclass must implement the run() method.")
# 
#     def stop(self) -> None:
#         """Dung driver va don dep TOAN BO tai nguyen (idempotent - goi nhieu lan van an toan)."""
#         if self._stopped:
#             return
#         self._stopped = True
# 
#         driver_pid = None
#         if self.driver is not None:
#             logger.info("Dang dong driver...")
#             try:
#                 driver_pid = self.driver.service.process.pid
#             except Exception:
#                 driver_pid = None
#             try:
#                 self.driver.quit()
#             except Exception as e:
#                 logger.warning(f"Error occurred while quitting driver (ignoring, will kill process): {e}")
#             finally:
#                 self.driver = None
# 
#         if driver_pid:
#             self._kill_process_tree(driver_pid)
# 
#         self._cleanup_orphan_processes()
#         self._remove_lock_files()
#         self._cleanup_profile_dir()
# 
#         self._is_running = False
#         logger.info("Cleanup done. Crawler stoped safely.")
# 
#     # ------------------------------------------------------------------ #
#     # Ho tro noi bo
#     # ------------------------------------------------------------------ #
#     def _resolve_profile_dir(self) -> None:
#         if self.user_data_dir:
#             # Thu muc GOC: chi tao neu chua co, KHONG BAO GIO bi xoa boi crawler.
#             root = Path(self.user_data_dir)
#             root.mkdir(parents=True, exist_ok=True)
# 
#             # Profile THAT SU nam trong 1 thu muc con do crawler tu quan ly ->
#             # day moi la thu muc co the bi xoa khi cleanup, thu muc goc luon an toan.
#             profile_dir = root / self.profile_name
#             profile_dir.mkdir(parents=True, exist_ok=True)
#             self._profile_dir = str(profile_dir.resolve())
#         else:
#             self._profile_dir = str(Path(tempfile.mkdtemp(prefix="crawler_profile_")).resolve())
# 
#     def _build_options(self) -> Options:
#         options = Options()
# 
#         # [COLAB] chi ro binary Edge tren Linux (neu co)
#         if os.path.exists(EDGE_LINUX_BINARY):
#             options.binary_location = EDGE_LINUX_BINARY
# 
#         if self.headless:
#             options.add_argument("--headless=new")
# 
#         options.add_argument(f"--user-data-dir={self._profile_dir}")
#         options.add_argument(f"--window-size={self.window_size}")
#         options.add_argument("--no-sandbox")
#         options.add_argument("--disable-dev-shm-usage")
#         options.add_argument("--disable-gpu")  # [COLAB] khong co GPU
#         options.add_argument("--disable-extensions")
#         options.add_argument("--disable-infobars")
#         options.add_argument("--disable-notifications")
#         options.add_argument("--blink-settings=imagesEnabled=false")
#         options.add_argument("--media-cache-size=1")
# 
#         if self.user_agent:
#             options.add_argument(f"--user-agent={self.user_agent}")
# 
#         for opt in self.extra_options:
#             options.add_argument(opt)
# 
#         return options
# 
#     def _kill_process_tree(self, pid: int) -> None:
#         """Kill toan bo tien trinh con (msedge.exe, msedgedriver.exe) cua 1 PID goc."""
#         try:
#             parent = psutil.Process(pid)
#         except psutil.NoSuchProcess:
#             return
#         try:
#             children = parent.children(recursive=True)
#         except psutil.NoSuchProcess:
#             children = []
#         for child in children:
#             try:
#                 child.kill()
#             except (psutil.NoSuchProcess, psutil.AccessDenied):
#                 pass
#         try:
#             parent.kill()
#         except (psutil.NoSuchProcess, psutil.AccessDenied):
#             pass
# 
#     def _cleanup_orphan_processes(self) -> None:
#         """
#         Kill moi tien trinh msedge.exe / msedgedriver.exe con dang dung dung
#         profile nay (bat ke cua phien nao) - phong khi quit()/kill theo PID
#         khong xu ly het, hoac lan chay truoc bi crash giua chung.
#         """
#         if not self._profile_dir:
#             return
# 
#         target = os.path.normcase(os.path.abspath(self._profile_dir))
#         killed = 0
#         for proc in psutil.process_iter(["name", "cmdline"]):
#             try:
#                 name = (proc.info["name"] or "").lower()
#                 if "msedge" not in name:
#                     continue
#                 cmdline = proc.info["cmdline"] or []
#                 cmdline_str = os.path.normcase(" ".join(cmdline))
#                 if target in cmdline_str:
#                     proc.kill()
#                     killed += 1
#             except (psutil.NoSuchProcess, psutil.AccessDenied):
#                 pass
# 
#         if killed:
#             logger.info(f"Killed {killed} orphan processes (profile: {self._profile_dir}).")
# 
#     def _remove_lock_files(self) -> None:
#         if not self._profile_dir:
#             return
#         for lock_name in ("SingletonLock", "SingletonCookie", "SingletonSocket"):
#             lock_path = Path(self._profile_dir) / lock_name
#             try:
#                 if lock_path.exists():
#                     lock_path.unlink()
#             except Exception:
#                 pass
# 
#     def _cleanup_profile_dir(self) -> None:
#         """
#         CHI xoa thu muc profile ma chinh crawler tao ra:
#             - Truong hop tam (khong truyen user_data_dir): xoa thu muc tam.
#             - Truong hop truyen user_data_dir: xoa (neu duoc yeu cau) thu muc con
#               `profile_name` NAM BEN TRONG user_data_dir. Thu muc GOC user_data_dir
#               khong bao gio bi dong den o day.
#         """
#         if not self._profile_dir or not Path(self._profile_dir).exists():
#             self._profile_dir = None
#             return
# 
#         should_delete = self._is_temp_profile or self._cleanup_user_data_dir
# 
#         if should_delete:
#             try:
#                 shutil.rmtree(self._profile_dir, ignore_errors=True)
#                 logger.info(f"Deleted profile directory (not deleting root directory): {self._profile_dir}")
#             except Exception as e:
#                 logger.warning(f"Cannot delete profile directory: {e}")
#         else:
#             logger.info(f"Retaining profile directory: {self._profile_dir}")
# 
#         self._profile_dir = None
# 
#     def _handle_signal(self, signum, frame):
#         logger.info(f"received signal {signum}, stopping crawler safely...")
#         self.stop()
#         # [COLAB] nut Stop cua Colab gui SIGINT -> raise KeyboardInterrupt de cell dung binh thuong
#         if signum == signal.SIGINT:
#             raise KeyboardInterrupt
#         raise SystemExit(0)
# 
#     def __enter__(self):
#         self.start()
#         return self
# 
#     def __exit__(self, exc_type, exc_val, exc_tb):
#         self.stop()
#         return False

import sys
sys.path.insert(0, '/content')
from base_crawler import BaseCrawler, logger
print('Import base_crawler OK')

"""### (Tuỳ chọn) Test nhanh Edge + driver có chạy được không"""

with BaseCrawler(driver_path=DRIVER_PATH, user_data_dir=USER_DATA_DIR + '_test',
                 cleanup_user_data_dir=True, headless=True, profile_name='test') as t:
    t.driver.get('https://example.com')
    print('Title:', t.driver.title)

"""## 6. Lưu trạng thái lên Drive (để resume)

Dùng 3 file dạng **append-only**, mỗi dòng 1 URL:

- `urls_found.txt`: mọi URL đã phát hiện (kể cả chưa crawl)
- `urls_done.txt`: URL đã crawl xong
- `urls_failed.txt`: URL lỗi quá `MAX_RETRIES` lần

Khi chạy lại: hàng đợi cần crawl = `found - done`. Dòng cuối bị ghi dở (do bị ngắt đột ngột) sẽ tự bị loại bỏ.
"""

import queue, threading

class CrawlStore:
    def __init__(self, data_dir):
        self.paths = {
            'found':  os.path.join(data_dir, 'urls_found.txt'),
            'done':   os.path.join(data_dir, 'urls_done.txt'),
            'failed': os.path.join(data_dir, 'urls_failed.txt'),
        }
        self.found_list = self._load('found')      # giữ thứ tự để BFS đúng thứ tự cũ
        self.found = set(self.found_list)
        self.done = set(self._load('done'))
        self.failed = set(self._load('failed'))

    def _load(self, kind):
        path = self.paths[kind]
        if not os.path.exists(path):
            return []
        with open(path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        # loại dòng cuối nếu bị ghi dở (không có \n)
        if lines and not lines[-1].endswith('\n'):
            lines = lines[:-1]
            with open(path, 'w', encoding='utf-8') as f:
                f.writelines(lines)
        return [l.strip() for l in lines if l.strip()]

    def add_found(self, url):
        self.found.add(url)
        self.found_list.append(url)

    def append(self, batch):
        """Ghi 1 batch [(kind, url), ...] xuống Drive."""
        grouped = {}
        for kind, url in batch:
            grouped.setdefault(kind, []).append(url)
        for kind in ('found', 'done', 'failed'):      # found luôn được ghi trước done
            urls = grouped.get(kind)
            if not urls:
                continue
            try:
                with open(self.paths[kind], 'a', encoding='utf-8') as f:
                    f.write(''.join(u + '\n' for u in urls))
                    f.flush()
                    os.fsync(f.fileno())
                logger.info(f'[writer] +{len(urls)} -> {os.path.basename(self.paths[kind])}')
            except OSError:
                logger.exception(f'[writer] ghi {kind} thất bại')

def writer_loop(store, write_q):
    stop = False
    while not stop:
        try:
            item = write_q.get(timeout=BATCH_TIMEOUT)
        except queue.Empty:
            continue
        batch = []
        if item is None:
            stop = True
        else:
            batch.append(item)
        while not stop and len(batch) < BATCH_SIZE:
            try:
                item = write_q.get_nowait()
            except queue.Empty:
                break
            if item is None:
                stop = True
                break
            batch.append(item)
        if batch:
            store.append(batch)

"""## 7. Logic crawl

Khác bản trước:
- Bỏ lệnh `Memory.forciblyPurgeJavaScriptMemory` (làm renderer của Edge bị treo/chết). Việc giải phóng RAM do restart driver đảm nhiệm.
- Tự phát hiện driver hỏng (lỗi liên tiếp) và restart; URL bị lỗi do driver hỏng **không** bị đánh dấu lỗi.
- Log lỗi gọn một dòng, không in traceback dài.
"""

import time, psutil
from collections import deque
from time import sleep
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException, WebDriverException

def standalize_url(url: str):
    if not url:
        return ""
    # Giữ lại số trang nếu là link danh mục (?page=), còn link sản phẩm thì cắt query param
    if '/c' in url and 'page=' in url:
        return url
    return url.split('?')[0].split('#')[0]

def short_err(e):
    msg = str(e).strip().splitlines()
    return f'{type(e).__name__}: {msg[0] if msg else ""}'

def get_driver_ram_mb(driver):
    """Tính tổng RAM thực của process Edge chính + các process con"""
    try:
        proc = psutil.Process(driver.service.process.pid)
        total = proc.memory_full_info().uss
        for child in proc.children(recursive=True):
            try:
                total += child.memory_full_info().uss
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
        return total / (1024 * 1024)
    except Exception:
        return None

def fmt_ram(ram):
    return f'{ram:.0f}MB' if ram is not None else 'n/a'

def scroll_down_page(driver):
    """Cuộn trang từng nấc để kích hoạt Lazy Loading của React/Next.js trên Tiki"""
    try:
        for step in [0.4, 0.8, 1.0]:
            driver.execute_script(f"window.scrollTo(0, document.body.scrollHeight * {step});")
            sleep(0.3)
    except Exception:
        pass

def producer_crawl(crawler, store, write_q, seed_urls, max_runtime_minutes=None):
    started = time.time()

    # --- KHỞI TẠO HOẶC RESUME TỪ DRIVE ---
    for seed in seed_urls:
        s_url = standalize_url(seed)
        if s_url not in store.found:
            store.add_found(s_url)
            write_q.put(('found', s_url))

    frontier = deque(u for u in store.found_list if u not in store.done)
    logger.info(f'Khởi động: found={len(store.found)} | done={len(store.done)} | hàng đợi={len(frontier)}')

    retries = {}
    pages_since_clear = 0
    pages_since_restart = 0
    consecutive_failures = 0
    restarts_without_success = 0

    while frontier:
        if max_runtime_minutes and (time.time() - started) / 60 >= max_runtime_minutes:
            logger.info('Hết thời gian chỉ định, dừng an toàn.')
            break

        url = frontier.popleft()
        if url in store.done:
            continue

        try:
            crawler.driver.get(url)
            scroll_down_page(crawler.driver)
            sleep(0.5)

            # --- 1. TỰ ĐỘNG BÓC CÁC DANH MỤC CON & MỞ RỘNG PHÂN TRANG (Nếu là trang danh mục) ---
            if '/c' in url:
                # Tự động quét các danh mục con trong menu/breadcrumb
                cat_elements = crawler.driver.find_elements(By.XPATH,
                    "//div[contains(@class, 'category') or contains(@class, 'Category') or contains(@class, 'filter')]//a[contains(@href, '/c')]"
                )
                for cat_el in cat_elements:
                    cat_href = cat_el.get_attribute('href')
                    if cat_href and 'tiki.vn' in cat_href and '/c' in cat_href:
                        clean_cat = standalize_url(cat_href)
                        if clean_cat not in store.found:
                            store.add_found(clean_cat)
                            frontier.append(clean_cat)
                            write_q.put(('found', clean_cat))

                # Tự động chuyển tiếp trang danh mục lên tới 50 trang (?page=1..50)
                curr_page = 1
                base_cat = url.split('?')[0]
                if 'page=' in url:
                    try:
                        curr_page = int(url.split('page=')[1].split('&')[0])
                    except Exception:
                        curr_page = 1
                if curr_page < 50:
                    next_page_url = f"{base_cat}?page={curr_page + 1}"
                    if next_page_url not in store.found:
                        store.add_found(next_page_url)
                        frontier.append(next_page_url)
                        write_q.put(('found', next_page_url))

            # --- 2. BÓC TÁCH LINK SẢN PHẨM ---
            elements = crawler.driver.find_elements(By.XPATH,
                "//a[contains(@class, 'product-item') or contains(@href, '-p')]"
            )
            raw_links = [el.get_attribute('href') for el in elements if el.get_attribute('href')]

        except (TimeoutException, WebDriverException) as e:
            consecutive_failures += 1
            logger.warning(f'Lỗi tải {url} ({consecutive_failures} lần liên tiếp) | {short_err(e)}')

            if consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                restarts_without_success += 1
                if restarts_without_success > MAX_RESTARTS_WITHOUT_SUCCESS:
                    frontier.appendleft(url)
                    logger.error('Driver lỗi liên tục nhiều lần, dừng crawler.')
                    break
                logger.warning('Nghi driver nghẽn -> Restart driver')
                try:
                    crawler.restart_driver()
                except Exception:
                    frontier.appendleft(url)
                    break
                consecutive_failures = 0
                pages_since_restart = 0
                pages_since_clear = 0
                frontier.appendleft(url)
                continue

            retries[url] = retries.get(url, 0) + 1
            if retries[url] <= MAX_RETRIES:
                frontier.append(url)
            else:
                store.done.add(url)
                store.failed.add(url)
                write_q.put(('failed', url))
                write_q.put(('done', url))
            continue

        consecutive_failures = 0
        restarts_without_success = 0

        # Lọc sạch và lưu các link sản phẩm (-p...html)
        for href in raw_links:
            if not href or 'tiki.vn' not in href or 'tka.tiki.vn' in href:
                continue
            clean_url = standalize_url(href)
            if '-p' in clean_url and clean_url.endswith('.html'):
                if clean_url in store.found:
                    continue
                store.add_found(clean_url)
                frontier.append(clean_url)
                write_q.put(('found', clean_url))

        # Đánh dấu xong URL hiện tại
        store.done.add(url)
        write_q.put(('done', url))

        pages_since_clear += 1
        pages_since_restart += 1

        # Dọn dẹp cache trình duyệt để kiểm soát bộ nhớ
        if pages_since_clear >= CLEAR_CACHE_EVERY_N_PAGES:
            try:
                crawler.driver.execute_cdp_cmd('Network.clearBrowserCache', {})
            except Exception:
                pass
            pages_since_clear = 0

        # Kiểm tra RAM và restart driver nếu vượt ngưỡng
        ram_mb = get_driver_ram_mb(crawler.driver)
        need_restart = pages_since_restart >= RESTART_DRIVER_EVERY_N_PAGES
        if ram_mb is not None and ram_mb > RESTART_DRIVER_RAM_MB:
            need_restart = True
        if need_restart:
            logger.info(f'Restarting driver định kỳ | RAM: {fmt_ram(ram_mb)}')
            try:
                crawler.restart_driver()
            except Exception:
                break
            pages_since_restart = 0
            pages_since_clear = 0

        logger.info(f'Frontier: {len(frontier)} | Found: {len(store.found)} | Done: {len(store.done)} | RAM: {fmt_ram(ram_mb)}')

class DiscoveryCrawler(BaseCrawler):
    def run(self, *args) -> None:
        seed_urls = args[0]
        store = CrawlStore(DATA_DIR)
        write_q = queue.Queue()

        writer = threading.Thread(target=writer_loop, args=(store, write_q), daemon=True)
        writer.start()
        try:
            producer_crawl(self, store, write_q, seed_urls, MAX_RUNTIME_MINUTES)
        finally:
            write_q.put(None)
            writer.join(timeout=60)
            logger.info(f'Kết thúc phiên: Found={len(store.found)} | Done={len(store.done)} | Failed={len(store.failed)}')

"""## 7b. (Chạy khi lần trước bị lỗi hàng loạt) Khôi phục URL bị đánh dấu lỗi oan

Nếu lần chạy trước driver bị hỏng, một số URL có thể đã bị ghi vào `urls_failed.txt` và `urls_done.txt` dù chưa crawl được. Cell này bỏ chúng khỏi `urls_done.txt` (có sao lưu `urls_done.backup.txt`) và xoá `urls_failed.txt`, để lần chạy tới crawl lại. Nếu `urls_failed.txt` trống hoặc không có thì cell không làm gì.
"""

failed_p = os.path.join(DATA_DIR, 'urls_failed.txt')
done_p   = os.path.join(DATA_DIR, 'urls_done.txt')

def _read(p):
    return [l.rstrip('\n') for l in open(p, encoding='utf-8')] if os.path.exists(p) else []

failed_urls = {u.strip() for u in _read(failed_p) if u.strip()}
if not failed_urls:
    print('Không có URL nào bị đánh dấu lỗi. Không cần khôi phục.')
else:
    done_lines = [u for u in _read(done_p) if u.strip()]
    shutil.copy2(done_p, os.path.join(DATA_DIR, 'urls_done.backup.txt'))
    kept = [u for u in done_lines if u.strip() not in failed_urls]
    with open(done_p, 'w', encoding='utf-8') as f:
        f.write(''.join(u + '\n' for u in kept))
        f.flush(); os.fsync(f.fileno())
    open(failed_p, 'w').close()
    print(f'Đã khôi phục {len(done_lines) - len(kept)} URL về hàng đợi (done: {len(done_lines)} -> {len(kept)}).')

"""## 8. Chạy crawler

- Nhấn **Stop** (hoặc Colab bị ngắt) thì dữ liệu đã ghi vẫn nằm trên Drive.
- Muốn **tiếp tục**: chạy lại cell 1 → 2 → 3 → 4 → 5 → 6 → 7 (định nghĩa lại) rồi chạy cell này. Crawler tự đọc `urls_found.txt` / `urls_done.txt` và đi tiếp.
"""

crawler = DiscoveryCrawler(
    driver_path=DRIVER_PATH,
    user_data_dir=USER_DATA_DIR,
    cleanup_user_data_dir=True,
    headless=True,
    profile_name='fashion_discovery',
)
crawler.start()
try:
    crawler.run(SEED_URLS)
finally:
    crawler.stop()

"""## 9. Xem kết quả / xuất CSV"""

import pandas as pd

def read_lines(name):
    p = os.path.join(DATA_DIR, name)
    return [l.strip() for l in open(p, encoding='utf-8')] if os.path.exists(p) else []

found, done, failed = map(read_lines, ('urls_found.txt', 'urls_done.txt', 'urls_failed.txt'))
print(f'Found: {len(found)} | Done: {len(done)} | Failed: {len(failed)} | Còn lại: {len(set(found) - set(done))}')

df = pd.DataFrame({'url': list(dict.fromkeys(found))})
df['crawled'] = df['url'].isin(set(done))
df.to_csv(os.path.join(DATA_DIR, 'urls_export.csv'), index=False, encoding='utf-8-sig')
df.head()

"""### (Tuỳ chọn) Xoá dữ liệu để crawl lại từ đầu
Bỏ dấu `#` ở các dòng dưới nếu muốn xoá trạng thái.
"""

# for f in ('urls_found.txt', 'urls_done.txt', 'urls_failed.txt'):
#     p = os.path.join(DATA_DIR, f)
#     if os.path.exists(p):
#         os.remove(p)
# print('Đã xoá trạng thái')