# -*- coding: utf-8 -*-
"""tiki_refresh_crawler_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hILq1D-LSmY_700YlxWsME_jtSPNHike

# Tiki Refresh Crawler (Selenium + MS Edge) chạy trên Google Colab

## 1. Mount Google Drive và cấu hình
"""

# [Cell 1] Mount Drive, cấu hình đường dẫn CỐ ĐỊNH và cài đặt thư viện
from google.colab import drive
import os

drive.mount('/content/drive')

# ====== CẤU HÌNH ĐƯỜNG DẪN CỐ ĐỊNH (KHÔNG DÙNG TIMESTAMP) ======
BASE_DIR        = '/content/drive/MyDrive/tiki_crawler'
DATA_DIR        = f'{BASE_DIR}/data'
INPUT_URLS_TXT  = f'{DATA_DIR}/urls_found.txt'

# Cố định duy nhất 1 thư mục output và 1 file CSV kết quả
OUTPUT_DIR      = f'{BASE_DIR}/csv_output/run_main'
OUTPUT_CSV      = f'{OUTPUT_DIR}/tiki_fashion_products.csv'
CHECKPOINT_DONE = f'{OUTPUT_DIR}/crawled_urls_done.txt'

LOCAL_DRIVER_DIR = '/content/edgedriver_linux64'
DRIVER_PATH      = f'{LOCAL_DRIVER_DIR}/msedgedriver'
USER_DATA_DIR    = '/content/selenium_user_data'

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(LOCAL_DRIVER_DIR, exist_ok=True)

print(f"📁 Thư mục lưu kết quả CỐ ĐỊNH: {OUTPUT_DIR}")
print(f"📄 File CSV duy nhất:            {OUTPUT_CSV}")
print(f"📑 File Checkpoint:             {CHECKPOINT_DONE}")

!pip -q install selenium psutil beautifulsoup4

"""## 2. Cài Microsoft Edge"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # [Cell 2] Cài Microsoft Edge Stable trên Linux Colab
# set -e
# apt-get update -qq
# apt-get install -y -qq wget gnupg unzip curl > /dev/null
# curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --yes -o /usr/share/keyrings/microsoft-edge.gpg
# echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
# apt-get update -qq
# apt-get install -y -qq microsoft-edge-stable > /dev/null
# microsoft-edge --version

"""## 3. Tải Edge WebDriver tương thích"""

# [Cell 3] Tự động tìm và cài đúng Edge WebDriver trên Linux Colab
import subprocess, re, os, zipfile, io, urllib.request

LOCAL_DRIVER_DIR = '/content/edgedriver_linux64'
DRIVER_PATH      = f'{LOCAL_DRIVER_DIR}/msedgedriver'
os.makedirs(LOCAL_DRIVER_DIR, exist_ok=True)

# 1. Lấy phiên bản Edge đang cài đặt ở Cell 2
try:
    edge_out = subprocess.check_output(['microsoft-edge', '--version'], text=True)
    edge_ver = re.search(r'(\d+\.\d+\.\d+\.\d+)', edge_out).group(1)
    major_ver = edge_ver.split('.')[0]
    print(f" Phiên bản Microsoft Edge: {edge_ver} (Major: {major_ver})")
except Exception as e:
    raise RuntimeError("Chưa cài Microsoft Edge! Hãy chạy lại Cell 2 trước.") from e

# 2. Danh sách các URL tải driver chính thức của Microsoft
candidate_urls = [
    f"https://msedgedriver.azureedge.net/{edge_ver}/edgedriver_linux64.zip",
    f"https://msedgedriver.microsoft.com/{edge_ver}/edgedriver_linux64.zip",
]

try:
    req = urllib.request.Request(f"https://msedgedriver.azureedge.net/LATEST_RELEASE_{major_ver}_LINUX", headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=10) as resp:
        latest_ver = resp.read().decode('utf-16').strip().lstrip('\ufeff')
        if latest_ver and latest_ver != edge_ver:
            candidate_urls.append(f"https://msedgedriver.azureedge.net/{latest_ver}/edgedriver_linux64.zip")
except Exception:
    pass

# 3. Tải và giải nén driver
success = False
for url in candidate_urls:
    print(f"Đang thử tải từ: {url} ...")
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=60) as response:
            zip_data = response.read()
            with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
                z.extractall(LOCAL_DRIVER_DIR)
            success = True
            print(" Tải và giải nén thành công!")
            break
    except Exception as err:
        print(f"  -> Thất bại ({err}), thử nguồn tiếp theo...")

if not success or not os.path.exists(DRIVER_PATH):
    raise FileNotFoundError(f"Không thể tải msedgedriver. Đường dẫn {DRIVER_PATH} vẫn chưa có file.")

os.chmod(DRIVER_PATH, 0o755)
driver_test = subprocess.check_output([DRIVER_PATH, '--version'], text=True)
print(f" Hoàn tất! Driver sẵn sàng: {driver_test.strip()}")

"""## 4. Khởi tạo module base_crawler.py trên Linux Colab"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/base_crawler.py
# import atexit
# import logging
# import os
# import shutil
# import signal
# import tempfile
# from abc import ABC
# from pathlib import Path
# from typing import Optional
# import psutil
# from selenium import webdriver
# from selenium.webdriver.edge.options import Options
# from selenium.webdriver.edge.service import Service
# 
# logging.basicConfig(
#     level=logging.INFO,
#     format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
#     force=True,
# )
# logger = logging.getLogger("ColabCrawler")
# 
# EDGE_LINUX_BINARY = "/opt/microsoft/msedge/msedge"
# 
# class BaseCrawler(ABC):
#     def __init__(
#         self,
#         headless: bool = True,
#         driver_path: Optional[str] = None,
#         user_data_dir: Optional[str] = None,
#         profile_name: str = "profile",
#         cleanup_user_data_dir: bool = True,
#     ):
#         self.headless = headless
#         self.driver_path = driver_path
#         self.user_data_dir = user_data_dir
#         self.profile_name = profile_name
#         self.cleanup_user_data_dir = cleanup_user_data_dir
#         self.driver = None
#         self._profile_dir = None
#         self._stopped = False
# 
#         atexit.register(self.stop)
#         signal.signal(signal.SIGINT, self._handle_signal)
#         signal.signal(signal.SIGTERM, self._handle_signal)
# 
#     def start(self) -> None:
#         self._resolve_profile()
#         options = Options()
#         if os.path.exists(EDGE_LINUX_BINARY):
#             options.binary_location = EDGE_LINUX_BINARY
#         if self.headless:
#             options.add_argument("--headless=new")
#         options.add_argument(f"--user-data-dir={self._profile_dir}")
#         options.add_argument("--window-size=1920,1080")
#         options.add_argument("--no-sandbox")
#         options.add_argument("--disable-dev-shm-usage")
#         options.add_argument("--disable-gpu")
#         options.add_argument("--disable-extensions")
#         options.add_argument("--blink-settings=imagesEnabled=false")
# 
#         service = Service(executable_path=self.driver_path) if self.driver_path else None
#         self.driver = webdriver.Edge(service=service, options=options)
#         self.driver.set_page_load_timeout(30)
#         self.driver.implicitly_wait(5)
#         logger.info("Driver khởi động hoàn tất.")
# 
#     def restart_driver(self):
#         logger.warning("Đang restart driver để giải phóng RAM...")
#         self.stop()
#         self.start()
# 
#     def stop(self) -> None:
#         if self._stopped:
#             return
#         self._stopped = True
#         pid = None
#         if self.driver:
#             try:
#                 pid = self.driver.service.process.pid
#                 self.driver.quit()
#             except Exception:
#                 pass
#             self.driver = None
#         if pid:
#             self._kill_proc(pid)
#         if self.cleanup_user_data_dir and self._profile_dir:
#             shutil.rmtree(self._profile_dir, ignore_errors=True)
#         logger.info("Driver đã dọn dẹp sạch sẽ.")
# 
#     def _resolve_profile(self):
#         self._stopped = False
#         root = Path(self.user_data_dir or tempfile.mkdtemp())
#         self._profile_dir = str(root / self.profile_name)
#         Path(self._profile_dir).mkdir(parents=True, exist_ok=True)
# 
#     def _kill_proc(self, pid):
#         try:
#             parent = psutil.Process(pid)
#             for c in parent.children(recursive=True):
#                 c.kill()
#             parent.kill()
#         except Exception:
#             pass
# 
#     def _handle_signal(self, signum, frame):
#         self.stop()
#         if signum == signal.SIGINT:
#             raise KeyboardInterrupt
#         raise SystemExit(0)

"""### 5. Bộ Bóc tách Dữ liệu Sản phẩm & Ghi CSV Định kỳ"""

# [Cell 5] Logic bóc tách 14 trường & Ghi nối tiếp vào 1 file CSV duy nhất
import csv
import re
import sys
from time import sleep, monotonic
from bs4 import BeautifulSoup
import psutil
from base_crawler import BaseCrawler, logger

sys.set_int_max_str_digits(0)

CACHE_CLEAR_INTERVAL = 25
RESTART_INTERVAL = 60
MAX_DRIVER_MEMORY_MB = 2000

CSV_FIELDNAMES = [
    "product_id",
    "title",
    "brand",
    "category_path",
    "price",
    "original_price",
    "discount_rate",
    "quantity_sold",
    "rating_average",
    "review_count",
    "seller_name",
    "is_official",
    "description",
    "url"
]

def parse_product_html(html: str, url: str) -> dict:
    soup = BeautifulSoup(html, 'html.parser')

    # 1. product_id
    p_id_match = re.search(r'-p(\d+)\.html', url)
    product_id = p_id_match.group(1) if p_id_match else ""

    # 2. title
    title_el = (
        soup.find('h1', {'class': re.compile(r'Title|title|Header', re.I)})
        or soup.find('h1')
    )
    title = title_el.get_text(strip=True) if title_el else ""

    # 3. brand
    brand_el = (
        soup.find('a', {'data-view-id': 'pdp_details_brand_name'})
        or soup.find('a', {'href': re.compile(r'/thuong-hieu/')})
    )
    brand = brand_el.get_text(strip=True) if brand_el else "No Brand"

    # 4. category_path (Breadcrumb)
    breadcrumb_els = soup.find_all('a', {'class': re.compile(r'Breadcrumb|breadcrumb')})
    if breadcrumb_els:
        crumbs = [el.get_text(strip=True) for el in breadcrumb_els if el.get_text(strip=True)]
        category_path = " > ".join(crumbs)
    else:
        nav_el = soup.find('div', {'class': re.compile(r'breadcrumb', re.I)})
        category_path = nav_el.get_text(" > ", strip=True) if nav_el else ""

    # 5. price & 6. original_price
    price_el = (
        soup.find('div', {'class': re.compile(r'current-price|flash-sale-price', re.I)})
        or soup.find('span', {'class': re.compile(r'current-price', re.I)})
    )
    price_text = price_el.get_text(strip=True) if price_el else ""
    price_num = "".join(filter(str.isdigit, price_text))
    price = int(price_num) if price_num else 0

    orig_price_el = (
        soup.find('span', {'class': re.compile(r'original-price', re.I)})
        or soup.find('div', {'class': re.compile(r'original-price', re.I)})
    )
    orig_price_text = orig_price_el.get_text(strip=True) if orig_price_el else ""
    orig_price_num = "".join(filter(str.isdigit, orig_price_text))
    original_price = int(orig_price_num) if orig_price_num else price

    # 7. discount_rate (%)
    discount_el = soup.find('span', {'class': re.compile(r'discount-rate|badge-percent', re.I)})
    if discount_el:
        disc_num = "".join(filter(str.isdigit, discount_el.get_text(strip=True)))
        discount_rate = int(disc_num) if disc_num else 0
    else:
        if original_price > price and original_price > 0:
            discount_rate = int(round((1.0 - (price / original_price)) * 100))
        else:
            discount_rate = 0

    # 8. quantity_sold
    sold_el = soup.find(string=re.compile(r'Đã bán', re.I))
    quantity_sold = 0
    if sold_el:
        raw_sold = sold_el.strip()
        k_match = re.search(r'([\d\.,]+)\s*k', raw_sold, re.I)
        if k_match:
            try:
                quantity_sold = int(float(k_match.group(1).replace(',', '.')) * 1000)
            except ValueError:
                quantity_sold = 0
        else:
            num_match = re.search(r'Đã bán\s*([\d\.,]+)', raw_sold, re.I)
            if num_match:
                num_only = "".join(filter(str.isdigit, num_match.group(1)))
                quantity_sold = int(num_only) if num_only else 0

    # 9. rating_average
    rating_el = soup.find('div', {'class': re.compile(r'rating|stars', re.I)})
    rating_average = 0.0
    if rating_el:
        r_match = re.search(r'(\d+(\.\d+)?)', rating_el.get_text(strip=True))
        if r_match:
            try:
                val = float(r_match.group(1))
                rating_average = val if val <= 5.0 else 0.0
            except ValueError:
                rating_average = 0.0

    # 10. review_count
    review_count = 0
    review_text_el = soup.find(string=re.compile(r'\(?\s*\d+\s*(đánh giá|nhận xét)\)?', re.I))
    if review_text_el:
        match_rev = re.search(r'(\d+)\s*(đánh giá|nhận xét)', review_text_el, re.I)
        if match_rev:
            review_count = int(match_rev.group(1))
    else:
        sub_review = soup.find('div', {'class': re.compile(r'review|quantity', re.I)})
        if sub_review:
            m = re.search(r'\((\d+)\)', sub_review.get_text())
            if m:
                review_count = int(m.group(1))

    # 11. seller_name
    seller_el = (
        soup.find('a', {'class': re.compile(r'seller-name|seller__name', re.I)})
        or soup.find('div', {'class': re.compile(r'seller-info', re.I)})
    )
    seller_name = seller_el.get_text(strip=True) if seller_el else ""

    # 12. is_official
    badge_official = soup.find(string=re.compile(r'Chính hãng|Tiki Trading|Official', re.I))
    is_official = 1 if badge_official or "tiki trading" in seller_name.lower() else 0

    # 13. description
    desc_el = (
        soup.find('div', {'class': re.compile(r'ToggleContent__View|product-description', re.I)})
        or soup.find('div', {'id': 'product-description'})
    )
    if desc_el:
        desc_raw = desc_el.get_text(" ", strip=True)
        description = re.sub(r'\s+', ' ', desc_raw)[:2000]
    else:
        description = ""

    # 14. url
    clean_url = url.split('?')[0].split('#')[0]

    return {
        "product_id": product_id,
        "title": title,
        "brand": brand,
        "category_path": category_path,
        "price": price,
        "original_price": original_price,
        "discount_rate": discount_rate,
        "quantity_sold": quantity_sold,
        "rating_average": rating_average,
        "review_count": review_count,
        "seller_name": seller_name,
        "is_official": is_official,
        "description": description,
        "url": clean_url
    }

def get_driver_memory_mb(driver) -> float:
    if not driver: return 0.0
    try:
        parent = psutil.Process(driver.service.process.pid)
        total = parent.memory_info().rss
        for child in parent.children(recursive=True):
            total += child.memory_info().rss
        return total / (1024 * 1024)
    except Exception:
        return 0.0

class CsvDetailCrawler(BaseCrawler):
    def __init__(self, output_csv_path, checkpoint_path, **kwargs):
        super().__init__(**kwargs)
        self.output_csv = output_csv_path
        self.checkpoint_path = checkpoint_path
        self._init_csv()

    def _init_csv(self):
        # Chỉ tạo header 1 lần duy nhất nếu file chưa tồn tại
        if not os.path.exists(self.output_csv) or os.path.getsize(self.output_csv) == 0:
            with open(self.output_csv, 'w', newline='', encoding='utf-8') as f:
                writer = csv.writer(f)
                writer.writerow(CSV_FIELDNAMES)

    def _crawl_one(self, url: str) -> str | None:
        try:
            t0 = monotonic()
            self.driver.get(url)
            t1 = monotonic()

            # Cuộn trang an toàn tránh lỗi scrollHeight
            for _ in range(6):
                sleep(0.08)
                try:
                    self.driver.execute_script("window.scrollBy(0, 700);")
                    new_h = self.driver.execute_script("return document.body ? document.body.scrollHeight : 0")
                    curr = self.driver.execute_script("return window.pageYOffset + window.innerHeight")
                    if new_h and curr >= new_h:
                        break
                except Exception:
                    break

            html = self.driver.page_source
            t2 = monotonic()
            logger.info(f"Crawl xong {url[:45]}... (load: {t1-t0:.2f}s, scroll: {t2-t1:.2f}s)")
            return html
        except Exception as e:
            logger.error(f"Lỗi truy cập {url}: {e}")
            return None

    def run(self, urls: list, batch_save_size=15):
        # 1. Đọc checkpoint để bỏ qua các link đã cào xong (Resume)
        done_urls = set()
        if os.path.exists(self.checkpoint_path):
            with open(self.checkpoint_path, 'r', encoding='utf-8') as f:
                done_urls = set(line.strip().split('?')[0] for line in f if line.strip())

        # 2. Lọc bỏ các URL đã làm
        pending_urls = [u for u in urls if u.split('?')[0] not in done_urls]
        logger.info(f"📊 Tổng link đầu vào: {len(urls):,} | Đã làm xong: {len(done_urls):,} | Cần cào tiếp: {len(pending_urls):,}")

        if not pending_urls:
            logger.info("🎉 Tất cả các link đã được cào xong hoàn toàn!")
            return

        urls_since_restart = 0
        batch_records = []
        batch_done = []

        try:
            for url in pending_urls:
                html = self._crawl_one(url)
                urls_since_restart += 1

                # Quản lý RAM & khởi động lại driver định kỳ
                if urls_since_restart % CACHE_CLEAR_INTERVAL == 0:
                    mem = get_driver_memory_mb(self.driver)
                    logger.info(f"Kiểm tra RAM: {mem:.1f} MB (duyệt {urls_since_restart} URL)")
                    if urls_since_restart >= RESTART_INTERVAL or mem > MAX_DRIVER_MEMORY_MB:
                        self.restart_driver()
                        urls_since_restart = 0
                    else:
                        try:
                            self.driver.execute_cdp_cmd("Network.clearBrowserCache", {})
                        except Exception:
                            pass

                if html:
                    record = parse_product_html(html, url)
                    batch_records.append(record)

                # Luôn đánh dấu hoàn thành link để không lặp lại khi bị lỗi
                batch_done.append(url.split('?')[0])

                # Ghi nối tiếp định kỳ xuống Drive
                if len(batch_records) >= batch_save_size:
                    self._flush_data(batch_records, batch_done)
                    batch_records.clear()
                    batch_done.clear()

            if batch_records or batch_done:
                self._flush_data(batch_records, batch_done)

        except KeyboardInterrupt:
            logger.info("Nhận thao tác dừng. Đang lưu nốt dữ liệu dang dở...")
            if batch_records or batch_done:
                self._flush_data(batch_records, batch_done)
        finally:
            logger.info("Hoàn tất phiên crawl.")

    def _flush_data(self, records, done_links):
        if records:
            with open(self.output_csv, 'a', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=CSV_FIELDNAMES)
                writer.writerows(records)

        if done_links:
            with open(self.checkpoint_path, 'a', encoding='utf-8') as f:
                for u in done_links:
                    f.write(f"{u}\n")
        logger.info(f"💾 Đã lưu +{len(records)} sản phẩm vào: {os.path.basename(self.output_csv)}")

"""## 6. Đọc URL từ Drive và Khởi chạy Pipeline"""

# [Cell 6] Tự động gộp dữ liệu cũ vào run_main và cào nối tiếp không trùng lặp
import glob
import pandas as pd
import os

# 1. Đọc danh sách link gốc từ Drive
urls_to_crawl = []
if os.path.exists(INPUT_URLS_TXT):
    with open(INPUT_URLS_TXT, 'r', encoding='utf-8') as f:
        urls_to_crawl = [line.strip().split('?')[0] for line in f if line.strip()]
else:
    print(f"❌ Không tìm thấy file {INPUT_URLS_TXT}!")

urls_to_crawl = list(dict.fromkeys([u for u in urls_to_crawl if '-p' in u and u.endswith('.html')]))
print(f"📌 Đã nạp danh sách: {len(urls_to_crawl):,} URL sản phẩm độc nhất.")

# 2. TỰ ĐỘNG GỘP TẤT CẢ DỮ LIỆU TỪ CÁC THƯ MỤC CŨ VÀO FILE run_main DUY NHẤT
old_csv_files = glob.glob(f'{BASE_DIR}/csv_output/run_*/tiki_fashion_products.csv')
all_dfs = []

# Đọc file hiện tại của run_main nếu đã có
if os.path.exists(OUTPUT_CSV) and os.path.getsize(OUTPUT_CSV) > 0:
    try:
        all_dfs.append(pd.read_csv(OUTPUT_CSV))
    except Exception:
        pass

# Đọc tất cả file CSV từ các run cũ
for f_path in old_csv_files:
    if 'run_main' not in f_path:
        try:
            df_old = pd.read_csv(f_path)
            if not df_old.empty:
                all_dfs.append(df_old)
        except Exception:
            pass

# Hợp nhất và khử trùng lặp
if all_dfs:
    df_merged = pd.concat(all_dfs, ignore_index=True)
    if 'url' in df_merged.columns:
        df_merged = df_merged.drop_duplicates(subset=['url'], keep='first')
    df_merged.to_csv(OUTPUT_CSV, index=False, encoding='utf-8')
    print(f"✅ Đã hợp nhất dữ liệu cũ! File CSV run_main hiện có: {len(df_merged):,} sản phẩm.")

    # Cập nhật lại checkpoint tương ứng với các URL đã có trong CSV
    existing_done_urls = set(df_merged['url'].dropna().str.split('?').str[0].tolist())
    with open(CHECKPOINT_DONE, 'w', encoding='utf-8') as f:
        for u in sorted(existing_done_urls):
            f.write(f"{u}\n")
    print(f"📑 Checkpoint đã cập nhật: {len(existing_done_urls):,} link đã hoàn tất.")

# 3. Khởi tạo và chạy Crawler nối tiếp
crawler = CsvDetailCrawler(
    output_csv_path=OUTPUT_CSV,
    checkpoint_path=CHECKPOINT_DONE,
    driver_path=DRIVER_PATH,
    user_data_dir=USER_DATA_DIR,
    profile_name="csv_detail_worker",
    headless=True,
    cleanup_user_data_dir=True
)

crawler.start()
try:
    crawler.run(urls_to_crawl, batch_save_size=15)
finally:
    crawler.stop()

# [Cell 7] Đọc và kiểm tra tổng tiến độ thực tế trong file run_main duy nhất
import os
import pandas as pd

if os.path.exists(OUTPUT_CSV):
    df_main = pd.read_csv(OUTPUT_CSV)
    total_records = len(df_main)
    unique_links = df_main['url'].nunique() if 'url' in df_main.columns else total_records

    done_urls_count = 0
    if os.path.exists(CHECKPOINT_DONE):
        with open(CHECKPOINT_DONE, 'r', encoding='utf-8') as f:
            done_urls_count = sum(1 for line in f if line.strip())

    print("=" * 60)
    print("       TIẾN ĐỘ THU THẬP TỔNG THỂ (RUN_MAIN DUY NHẤT)")
    print("=" * 60)
    print(f"• Tổng số sản phẩm trong CSV:   {total_records:>8,} dòng")
    print(f"• Số URL độc nhất đã lưu:      {unique_links:>8,} link")
    print(f"• Đã duyệt qua (Checkpoint):    {done_urls_count:>8,} URL")
    print(f"• Tiến độ hoàn thành:           {(done_urls_count / 29015) * 100:>7.2f}% (còn lại {29015 - done_urls_count:,} link)")
    print("=" * 60)
    display(df_main.tail(5))
else:
    print("Chưa tìm thấy file CSV tại run_main.")

"""## 7. Xem trước dữ liệu CSV đã lưu trên Google Drive"""

# [Cell 7] Đọc nhanh và kiểm tra file CSV kết quả
if os.path.exists(OUTPUT_CSV):
    df_result = pd.read_csv(OUTPUT_CSV)
    print(f"Tổng số bản ghi đã lưu: {len(df_result):,} dòng")
    display(df_result.head(10))
else:
    print("Chưa có file CSV nào được tạo.")