# -*- coding: utf-8 -*-
"""tiki_filter_fashion_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiguVRZlLwrlRJoULR4ojZgk31rrBCIc

# Lọc dữ liệu Tiki theo ngành hàng Thời trang

Notebook này đọc file CSV đã crawl (`csv_output/run_*/tiki_fashion_products.csv`), phân loại từng sản phẩm theo **cột `category_path`** (breadcrumb), rồi **ghi bản đã lọc sang một thư mục MỚI**.

**Dữ liệu cũ không bị đụng tới:** chỉ đọc file đầu vào, mọi file kết quả ghi vào `fashion_filtered/<FILTER_NAME>/`. Có kiểm tra chặn việc ghi nhầm vào thư mục dữ liệu cũ.

## Cách phân loại
Breadcrumb của Tiki có dạng `Trang chủ > Thời trang nam > Đồ lót nam > ...`. Notebook lấy **danh mục cấp 1** (ngay sau "Trang chủ") rồi so khớp theo từ khoá, không phân biệt hoa thường hay dấu tiếng Việt (nên `Giày - Dép nam` và `Giay dep nam` là một):

| Nhóm | Điều kiện | Ví dụ | Ghi ra |
|---|---|---|---|
| **fashion** | cấp 1 chứa `thời trang` hoặc `giày dép` | Thời trang nam, Thời trang nữ, Giày - Dép nam/nữ, Túi thời trang nam/nữ, Phụ kiện thời trang | `tiki_fashion_products.csv` |
| **optional** | cấp 1 là Balo/Vali/Đồng hồ/Trang sức, hoặc cấp 2-3 có từ khoá thời trang nằm trong ngành khác (ví dụ *Đồ chơi - Mẹ & Bé > Thời trang cho bé*) | Balo và Vali, Đồng hồ và Trang sức | `fashion_related_optional.csv` (tách riêng, bạn tự quyết định lấy hay không) |
| **other** | còn lại | Nhà Sách Tiki, Điện thoại... | không ghi (có đếm trong báo cáo) |
| **unclassified** | `category_path` trống | | `unclassified_for_review.csv` để kiểm tra |

Cell 3 in **bảng đếm theo danh mục** để bạn kiểm tra trước khi ghi file; nếu muốn thêm/bớt danh mục, chỉnh từ khoá ở cell 1 rồi chạy lại từ cell 2.

## 1. Mount Drive và cấu hình
"""

# [Cell 1] Cấu hình đường dẫn và danh mục phân loại mới
from google.colab import drive
drive.mount('/content/drive')

import os, glob, re, shutil, hashlib, unicodedata
import pandas as pd

# ====== ĐƯỜNG DẪN ======
BASE_DIR        = '/content/drive/MyDrive/tiki_crawler'
INPUT_CSV_PATH  = f'{BASE_DIR}/csv_output/run_main/tiki_fashion_products.csv'

FILTER_NAME = 'run_split_core_vs_outlier'
OUTPUT_DIR  = f'{BASE_DIR}/fashion_filtered/{FILTER_NAME}'

DEDUP_BY_URL = True

# ====== DANH MỤC THỜI TRANG CỐT LÕI + ĐỒNG HỒ, TRANG SỨC, KÍNH ======
# Gồm Thời trang (quần áo, giày dép, túi, phụ kiện/kính) + Đồng hồ & Trang sức
FASHION_CORE_KEYWORDS = ['thoi trang', 'giay dep', 'dong ho', 'trang suc']

# ====== DANH MỤC ĐƯA VÀO NGOẠI LAI (OUTLIERS) ======
# Đưa thẳng Balo và Vali sang nhóm ngoại lai
OUTLIER_FORCE_KEYWORDS = ['balo', 'vali']

os.makedirs(OUTPUT_DIR, exist_ok=True)
print('File đầu vào:', INPUT_CSV_PATH)
print('Thư mục kết quả mới:', OUTPUT_DIR)

"""## 2. Đọc dữ liệu và phân loại

Đọc mọi cột dưới dạng chữ để giữ nguyên giá trị gốc (không bị biến `NaN` hay đổi kiểu số). Dòng trùng URL giữa các file `run_*` được gộp lại.
"""

# [Cell 2] Đọc dữ liệu, phân loại 2 nhóm: Core Fashion vs Outliers
print(f'Đang đọc dữ liệu từ: {os.path.basename(INPUT_CSV_PATH)}...')
df = pd.read_csv(INPUT_CSV_PATH, dtype=str, keep_default_na=False)

for col in ('category_path', 'url', 'product_id', 'title', 'brand'):
    if col not in df.columns:
        df[col] = ''

df['product_id'] = df['product_id'].str.replace(r'\.0$', '', regex=True)

if DEDUP_BY_URL:
    df = df.drop_duplicates(subset=['url'], keep='first').reset_index(drop=True)
    print(f'Sau khi bỏ trùng URL: {len(df):,} dòng')

def norm(s):
    s = str(s).lower().replace('đ', 'd')
    s = unicodedata.normalize('NFD', s)
    s = ''.join(ch for ch in s if unicodedata.category(ch) != 'Mn')
    return re.sub(r'[^a-z0-9]+', ' ', s).strip()

def has_kw(text, keywords):
    padded = f' {norm(text)} '
    return any(f' {norm(k)} ' in padded for k in keywords)

def split_path(path):
    parts = [p.strip() for p in str(path).split('>') if p.strip()]
    if parts and norm(parts[0]) == 'trang chu':
        parts = parts[1:]
    return parts

def classify_record(path):
    parts = split_path(path)
    if not parts:
        return 'unclassified', ''

    root = parts[0]

    # 1. Balo & Vali đưa thẳng vào nhóm ngoại lai
    if has_kw(root, OUTLIER_FORCE_KEYWORDS):
        return 'outlier', root

    # 2. Thời trang cốt lõi + Đồng hồ & Trang sức
    if has_kw(root, FASHION_CORE_KEYWORDS):
        return 'fashion_core', root

    # 3. Quét kiểm tra cấp lồng (nested) cho thời trang trẻ em lồng trong Mẹ & Bé
    for crumb in parts[1:3]:
        if has_kw(crumb, ['thoi trang']):
            return 'fashion_core', root

    # 4. Còn lại là dữ liệu ngoại lai
    return 'outlier', root

res = df['category_path'].map(classify_record)
df['bucket'] = res.map(lambda x: x[0])
df['category_root'] = res.map(lambda x: x[1])

print("\n--- Thống kê số lượng theo nhóm ---")
print(df['bucket'].value_counts().to_string())

"""## 3. Kiểm tra bảng đếm theo danh mục (trước khi ghi file)

Mỗi dòng là một danh mục cấp 1. Cột `bucket` cho biết nó được xếp vào nhóm nào. Nếu thấy danh mục nào xếp sai, chỉnh từ khoá ở cell 1 rồi chạy lại từ cell 2.
"""

# [Cell 3] Kiểm tra bảng đếm theo danh mục (Đã sửa lỗi match_reason)
summary = (df.groupby(['bucket', 'category_root']).size()
             .reset_index(name='rows').sort_values('rows', ascending=False).reset_index(drop=True))
summary['pct'] = (summary['rows'] / len(df) * 100).round(2)

print('--- DANH MỤC THỜI TRANG CỐT LÕI + TRANG SỨC (FASHION_CORE) ---')
display(summary[summary['bucket'] == 'fashion_core'])

print('\n--- 20 DANH MỤC NGOẠI LAI + BALO VALI (OUTLIER) ---')
display(summary[summary['bucket'] == 'outlier'].head(20))

"""## 4. Ghi kết quả vào thư mục mới

Chỉ ghi vào `OUTPUT_DIR`. Thêm 2 cột vào bản lọc: `category_root` (danh mục cấp 1) và `match_reason` (`root` hoặc `nested`).
"""

# [Cell 4] Ghi 2 file CSV riêng biệt vào Google Drive
orig_cols = [c for c in df.columns if c not in ('bucket', 'category_root')]
out_cols = orig_cols + ['category_root']

# 1. Tách các tập dữ liệu
df_fashion_core = df[df['bucket'] == 'fashion_core']
df_outliers     = df[df['bucket'] == 'outlier']
df_unclassified = df[df['bucket'] == 'unclassified']

# 2. Lưu File 1: Thời trang cốt lõi + Đồng hồ, Trang sức, Kính mắt
path_file_core = os.path.join(OUTPUT_DIR, 'tiki_fashion_core_jewelry.csv')
df_fashion_core[out_cols].to_csv(path_file_core, index=False, encoding='utf-8-sig')

# Lưu riêng file TXT link thời trang cốt lõi
with open(os.path.join(OUTPUT_DIR, 'urls_fashion_core_jewelry.txt'), 'w', encoding='utf-8') as f:
    f.write(''.join(u + '\n' for u in df_fashion_core['url'] if u))

# 3. Lưu File 2: Dữ liệu ngoại lai (bao gồm Balo, Vali, Sách, Gia dụng...)
path_file_outlier = os.path.join(OUTPUT_DIR, 'tiki_outliers_and_luggage.csv')
df_outliers[out_cols].to_csv(path_file_outlier, index=False, encoding='utf-8-sig')

# 4. Lưu File phụ: Chưa phân loại (nếu có)
if len(df_unclassified) > 0:
    path_file_unclass = os.path.join(OUTPUT_DIR, 'unclassified_for_review.csv')
    df_unclassified[out_cols].to_csv(path_file_unclass, index=False, encoding='utf-8-sig')

print("=" * 65)
print(f"✅ ĐÃ TÁCH FILE THÀNH CÔNG VÀO: {OUTPUT_DIR}")
print(f"📁 1. File Thời trang cốt lõi + Trang sức: {len(df_fashion_core):>8,} dòng")
print(f"📁 2. File Ngoại lai + Balo Vali:          {len(df_outliers):>8,} dòng")
if len(df_unclassified) > 0:
    print(f"📁 3. File Chưa phân loại:                {len(df_unclassified):>8,} dòng")
print("=" * 65)